# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'latest'  # or specify a specific version if needed

      # Cache Flutter dependencies
      - name: Cache Flutter pub dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            !~/.pub-cache/bin
            !~/.pub-cache/hosted
            !~/.pub-cache/git
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install dependencies
        run: flutter pub get

      # Analyze project source
      - name: Analyze project source
        run: flutter analyze

      # Run tests
      - name: Run tests
        run: flutter test

      # Build Android
      - name: Build Android
        run: flutter build apk --release

  build-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'latest'  # or specify a specific version if needed
      - name: Install dependencies
        run: flutter pub get
      - name: Build iOS
        run: flutter build ios --release
